fix bug with DELETE, Add PUT
HandspikeDuck/DroolMissle pull request #1
Opened 2022-05-18 18:08 UTC by avolosin

There was some other weirdness where the project couldn't find the tests.

2022-05-31 17:51 UTC, HandspikeDuck requested changes
please remove .DS_Store from the tests project (and potentially add it to .gitignore)

also, do we know why there are changes to DroolMissle.Tests? (files seemed renamed?)

2022-05-31 17:51 UTC, HandspikeDuck commented on src/DroolMissle.HttpTester/HttpClientExtensions.cs
> +            var capture = new HttpRequestCapture() { Url = uri, Method = HttpMethod.Post, RequestStartTime = DateTime.UtcNow };
HttpMethod here is `Post` but this is supposed to be a `Put` correct?

2022-05-31 17:51 UTC, HandspikeDuck commented on src/DroolMissle.HttpTester/HttpClientExtensions.cs
> +            var response = await client.DeleteAsync(uri);
👍

2022-06-01 15:16 UTC, avolosin commented on src/DroolMissle.HttpTester/HttpClientExtensions.cs
> +            var capture = new HttpRequestCapture() { Url = uri, Method = HttpMethod.Post, RequestStartTime = DateTime.UtcNow };
Changed to a PUT

2022-06-01 15:17 UTC, avolosin commented
Not sure why the test project was renamed. I just opened it in VS.

2022-07-14 04:38 UTC, closed without merging

2022-07-14 04:38 UTC, HandspikeDuck commented
closed. changes cherry picked and pushed via cleanup branch.